### PR TITLE
Extract statements api

### PR DESCRIPTION
**Pull request by Giorgi**
Remaining tasks before it can be merged:

- [ ] Tests
- [ ] Check error message marshaling on non-Windows platforms

### CODE REVIEW

**Comment by Seddryck** [comment]
Hi Giorgi, I'm a bit not sure about the implementation but I'm clearly not a specialist of DuckDB so I could miss the point. 

In ADO.Net the class DbCommand handles a single command, when you have multiple commands, it's the class DbBatch that is handling that. It doesn't sound too important but my fear is especially regarding the method ExecuteReader where the classical behaviour is impacted. Merging together the readers isn't intuitive for me and my experience of ADO.net

**Comment by Giorgi** [comment]
You definitely can execute multiple statements with a single command:

[Retrieving multiple result sets using NextResult](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-data-using-a-datareader?redirectedfrom=MSDN#retrieving-multiple-result-sets-using-nextresult)

**Comment by Seddryck** [comment]
Yes, correct. Nevertheless, .NET introduced the Batch API (materialized by the DbBatch class) a couple of years ago mainly because the feature to support multiple statements into a single DbCommand was clumsy. See https://www.infoq.com/news/2022/06/Database-Command-Batching/

In a modern ADO.Net provider, it sounds more suitable to implement this in a DbBatch class than a DbCommand class. If you want I can create a pull request with an implementation of DbBatch. Optionally, we could use the same trick as PostgreSQL to allow/deny this option on the DbCommand class (Probably won't be able to do it in the next two weeks).

**Comment by Giorgi** [comment]
Yes, it would be nice to implement the Batch API but I think it should be left in the `DbCommand ` class too. Two weeks is perfectly OK, I plan to release a new version in May once DuckDB 0.8 is released. I'll create a ticket and you can assign it to you if you plan to work on it.

**Comment by Giorgi** [comment]
Created https://github.com/Giorgi/DuckDB.NET/issues/105

**Pull request merged**
