### PR TITLE
Add Apple Silicon support

### PR DESCRIPTION
**Pull request by rubiktubik**
I'am trying to use the awesome library on my M1 Pro Mac with arm64 but i'am getting System.DllNotFoundException: Unable to load shared library 'duckdb' or one of its dependencies. errors.

It seems that just the osx-arm64 runtime is missing.
This is my attempt to fix this problem and i hope this change is enought and the osx-universal also work on arm64.

Please feel free to correct my small attempt :-)

### CODE REVIEW

**Comment by Giorgi** [comment]
@rubiktubik The build failed because the delimiter for `RuntimeIdentifiers` should be `;` not `,` but I think instead of adding a new rid, just replacing `osx-x64` with `osx` should work according to [runtime.json](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L2586)

**Comment by rubiktubik** [comment]
Hmm, still failing on macos 🤔

**Comment by Giorgi** [comment]
@rubiktubik Do the tests run successfully locally?

**Comment by rubiktubik** [comment]
I'll test this on my Mac when I get home tonight and let you know.

**Comment by Giorgi** [comment]
I think you'll need to update [ModuleInit](https://github.com/Giorgi/DuckDB.NET/blob/main/DuckDB.NET.Test/ModuleInit.cs#L48) so that it returns `osx-arm64` if it's running on Arm

**Comment by Giorgi** [comment]
@rubiktubik Can you try installing [DuckDB.NET.Data.Full 0.7.2-alpha.21](https://github.com/users/Giorgi/packages/nuget/DuckDB.NET.Data.Full/87576226) to see if it works for you?

**Comment by rubiktubik** [comment]
The System.DllNotFoundException error ist gone! Thanks for your fast responses and effort! 

I now have this error `INTERNAL Error: Calling GetStorage on a TableCatalogEntry that is not a DTableCatalogEntry` but i think i'am just using the appender wrong.

**Comment by Giorgi** [comment]
Nice! Are you able to run tests locally?

**Comment by rubiktubik** [comment]
I can use your alpha nuget in my own project without a problem. 

But when i check out your develop branch and run the tests locally i still get the System.DllNotFoundException error

**Pull request merged**
