### PR TITLE
Add bindings for appender API.

### PR DESCRIPTION
**Pull request by kmosegaard**
This PR adds bindings for the appender API. Definitions are sourced from here: [https://duckdb.org/docs/api/c/appender](https://duckdb.org/docs/api/c/appender). Not all definitions are defined in this PR but is more than enough for my use-case.

What do you think, so I add the last ones for completeness?

### CODE REVIEW

**Comment by Giorgi** [comment]
If you can it would be nice to have the full API for the appender.

**Comment by Giorgi** [comment]
@kmosegaard Do you plan to resolve the conflicts or should I close the PR?

**Comment by kmosegaard** [comment]
Resolved conflicts.

I've also added the 'xunit.runner.visualstudio' because I wasn't able to run unit tests through 'dotnet test' without.
On test seems to be failing but is unrelated to this change?

**Comment by Giorgi** [comment]
Yes, it looks like concurrency issue between tests.

**Comment by Giorgi** [comment]
Thanks @kmosegaard!

**Pull request merged**
