### PR TITLE
Fixed threading issues with managing connections

### PR DESCRIPTION
**Pull request by SartorialOffense**
Hi thanks for creating this project! I did see a threading issue with the connection caching and fixed it: pushed all the logic for connections into a ConnectionManager class, added/renamed some of the internal stuff and put into Internal folder so the main classes didn't get crowded. Added testing project to verify the bug was fixed. Let me know if you need me to change anything.

### CODE REVIEW

**Comment by Giorgi** [comment]
@SartorialOffense Thanks for taking the time to send a PR!

Is it possible to implement it with `ConcurrentDictionary` and avoid locking the dictionary?

**Comment by SartorialOffense** [comment]
I tried to do that initially by keeping the concurrent dictionary and
locking on each database file reference while being changed, but I kept
running into scenarios where bad things would happen. I figured out a way
to do it (I think) today.  Let me play with it a couple days this week. The
trick is that on disposal/removal of the file reference, you need to
anticipate the case where while that is happening, another thread might
have just taken a lock on the same file reference object.  So you have to
put it back in the dictionary and undispose once you acquire the lock.

It does make bugs more likely because you can't simply use lock() on each
file reference.  You have to use Monitor.Enter() and Exit() and handle any
errors.

**Comment by Giorgi** [comment]
I'll accept the PR as is and if you make changes you can send a new one.

**Comment by SartorialOffense** [comment]
Great, I just put one in.  Seems to work pretty well and is indeed a couple
times faster under heavy multithreaded load.

**Pull request merged**
