### PR TITLE
Support shared in-memory databases

### PR DESCRIPTION
**Pull request by yxmm-wxe**
Try to implement #86.

### CODE REVIEW

**Comment by yxmm-wxe** [comment]
@Giorgi It was found that `Build library (windows-latest)` and `Build library (macos-12) ` are successful, while `Build library (ubuntu-20.04)` failed.

Comparison found that `pack` and `Upload Artifacts` are disabled in `Build library (windows-latest)` and `Build library (macos-12) `, while they are enabled in `Build library (ubuntu-20.04)`.

Is there anything I can do about this?

**Comment by Giorgi** [comment]
I added a condition to the CI and it should skip that step now for pull request builds. Can you pull the changes from my develop branch to your fork?

**Comment by Giorgi** [comment]
@yxmm-wxe 

It's creating on-disk databases `DataSource=:memory:?cache=shared` connection string.

image

**Comment by yxmm-wxe** [comment]
@Giorgi Sorry for my carelessness, something is missing. I have fixed the issue.

**Comment by Giorgi** [comment]
Thanks @yxmm-wxe it works fine now. I think the `Duplicate` method isn't required. You can create a new connection with the same connection string if you need to. What do you think?

**Comment by yxmm-wxe** [comment]
@Giorgi Yes, what you said could work for `DataSource=:memory:?cache=shared` and other on-disk databases.

But according to the current design, it will create an isolated in-memory database via `DataSource=:memory:`, and only one connection can be used. I don't think this can be used as a special case.

The `Duplicate` method can create another connection for the existing isolated in-memory database. And it was also supported in JDBC and Python.

**Comment by Giorgi** [comment]
I see but why not use the connection that you have? Why the need to Duplicate it?

**Comment by yxmm-wxe** [comment]
I found [duckdb_connect instruction](https://duckdb.org/docs/archive/0.7.1/api/c/connect#:~:text=With%20the%20duckdb_database%20handle%2C%20you%20can%20create%20one%20or%20many%20duckdb_connection%20using%20duckdb_connect().%20While%20individual%20connections%20are%20thread%2Dsafe%2C%20they%20will%20be%20locked%20during%20querying.%20It%20is%20therefore%20recommended%20that%20each%20thread%20uses%20its%20own%20connection%20to%20allow%20for%20the%20best%20parallel%20performance.) in the official documents. It is recommended that each thread uses its own connection to allow for the best parallel performance.

**Comment by colombod** [comment]
is this feature released on nuget.org?

**Comment by Giorgi** [comment]
Not yet but you can get it from [GitHub Packages](https://github.com/users/Giorgi/packages?repo_name=DuckDB.NET)

**Comment by colombod** [comment]
> Not yet but you can get it from [GitHub Packages](https://github.com/users/Giorgi/packages?repo_name=DuckDB.NET)

I would need it from nuget.org, I am building a kernel around your package to make it usable in Polyglot Notebooks (https://github.com/colombod/dotnet-interactive-extension-lab/pull/31) so far all look, would love to talk with you if you have time

**Pull request merged**
