### PR TITLE
added GetSchemaTable to datareader

### PR DESCRIPTION
**Pull request by mikeTWC1984**
This should allow to load DataTable from Reader. 
https://github.com/Giorgi/DuckDB.NET/issues/65

### CODE REVIEW

**Comment by Giorgi** [comment]
@mikeTWC1984 Can you add a test that shows what issue this PR solves?

**Comment by mikeTWC1984** [comment]
It lets loading reader data into datatable. Possible test is below.  Without GetSchemaTable method _dt.Load(reader)_ would throw an exception.

```csharp

    [Fact]
    public void LoadDataTable()
    {
        using var connection = new DuckDBConnection("DataSource=:memory:");
        connection.Open();

        var duckDbCommand = connection.CreateCommand();
        duckDbCommand.CommandText = "select 1 as num, 'text' as str, now() as tme";
        var reader = duckDbCommand.ExecuteReader();
        var dt = new DataTable()
        dt.Load(reader)
        dt.Rows.Count.Should().Be(1)
    }
```

**Comment by Giorgi** [comment]
Can you add that test to the PR?

**Comment by mikeTWC1984** [comment]
Just added

**Comment by mikeTWC1984** [comment]
just fixed missing semicolon

**Comment by mikeTWC1984** [comment]
I see test failing because "now()" returns a timestamp with milliseconds, by some reason reader.GetDateTime method can't handle it.
If I use timestamp from literal without ms, (e.g. "TIMESTAMP '1992-09-20 20:38:40'") it works.
I can also get string value from "now" ( reader.GetString) and cast it to ts.

**Comment by Giorgi** [comment]
@mikeTWC1984 Yes, please replace `now` with some literal and create an issue for milliseconds issue.

**Pull request merged**
