### PR TITLE
Make duckdb connection string support unicode path

### LINKED ISSUE #196: Can't use unicode for connectionstring
```csharp
var path = Path.Combine(AppContext.BaseDirectory, "中文");
if (!Directory.Exists(path))
{
    Directory.CreateDirectory(path);
}
var connstr = new DuckDBConnectionStringBuilder();
connstr.DataSource = Path.Combine(path, "中文.db");
var db = new DuckDBConnection(connstr.ConnectionString);
db.Open();
```

will throw exception

```
DuckDB.NET.Data.DuckDBException:“DuckDBOpen failed: IO Error: Cannot open file "C:\Users\huaji\Desktop\c\npnp\bin\Debug\net8.0\����\����.db": ϵͳ�Ҳ���ָ����·����
”
```

### PR DESCRIPTION
**Pull request by Cricle**
Fix #196

### CODE REVIEW

**Review by Giorgi — COMMENTED** [review]
I think the logic for converting string to handle belongs to the Data project. The Bindings project should contain only method definitions

**Comment by Cricle** [comment]
> I think the logic for converting string to handle belongs to the Data project. The Bindings project should contain only method definitions

The `NativeMethods.Startup.DuckDBOpen` will be a breakchang

**Comment by Giorgi** [comment]
You don't need to delete existing methods, just add a new overload.

**Comment by Cricle** [comment]
If I make it overload method, can accept it?
```csharp
NativeMethods.Startup.DuckDBOpen(null,out _);//<--- compile error, because the compiler unable to decide what method to execute.
```

**Comment by Giorgi** [comment]
You can cast null to the desired type to help the compiler.

**Comment by Cricle** [comment]
What about that?
```csharp
[DllImport(DuckDbLibrary, CallingConvention = CallingConvention.Cdecl, EntryPoint = "duckdb_open")]
public static extern DuckDBState DuckDBOpen(SafeUnmanagedMemoryHandle path, out DuckDBDatabase database);

[DllImport(DuckDbLibrary, CallingConvention = CallingConvention.Cdecl, EntryPoint = "duckdb_open")]
public static extern DuckDBState DuckDBOpen(string? path, out DuckDBDatabase database);

//Usage
NativeMethods.Startup.DuckDBOpen((string?)null,out _);
```

**Comment by Cricle** [comment]
Completed

**Comment by Giorgi** [comment]
You should not put logic in `NativeMethods.Startup`, just new overloads and call the correct one from the Data project.

**Comment by Cricle** [comment]
I may not quite understand what you mean, can you explain it in detail?

**Comment by Giorgi** [comment]
Yeah, that's what I meant.

**Pull request merged**
